name: Moonshot Testing

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  run-moonshot-in-ci:
    runs-on: ubuntu-latest
    environment: dev
    container:
      image: moonshotseanyctest-czgbd0c4dadjgmg2.azurecr.io/moonshot:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}   
        password: ${{ secrets.ACR_PASSWORD }} 
    steps:
      - name: Run Moonshot 
        run: |
          cd /app
          export OPENAI_API_KEY="${{ secrets.OPENAI_TOKEN }}"
          export AZURE_BLOB_STORAGE_URL="${{ secrets.AZURE_BLOB_STORAGE_URL }}"
          export AZURE_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
          export AZURE_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}"
          export AZURE_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
          export MS_TEST_CONFIG_PATH="${{ secrets.AZURE_MS_TEST_CONFIG_PATH }}"
          export MS_CONFIG_PATH="${{ secrets.AZURE_MS_CONFIG_PATH }}"

          moonshot run my-run-1 qa-tests my-gpt-4o-mini
      
      - name: Copy Results
        run: cp -r /app/data/results $GITHUB_WORKSPACE/results
      
      - name: Upload Moonshot Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /app/data/results/*  
        
