name: Moonshot Testing

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  authenticate_azure_services:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into Azure Container Registry
        uses: docker/login-action@v3
        with: 
          registry: moonshotseanyctest-czgbd0c4dadjgmg2.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}   
          password: ${{ secrets.ACR_PASSWORD }} 
      
      - name: Install Azure CLI 
        run: | 
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
      
      - name: Azure Login
        uses: azure/login@v2 
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}   
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}   
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
  run-moonshot-in-ci:
    runs-on: ubuntu-latest
    environment: dev
    needs: authenticate_azure_services
    container:
      image: moonshotseanyctest-czgbd0c4dadjgmg2.azurecr.io/moonshot:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}   
        password: ${{ secrets.ACR_PASSWORD }} 
    steps:
      - name: Run Moonshot 
        run: |
          cd /app
          export OPENAI_API_KEY="${{ secrets.OPENAI_TOKEN }}"
          export AZURE_BLOB_STORAGE_URL=${{ secrets.AZURE_BLOB_STORAGE_URL }}
          export AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          export AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          export AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
          export MS_TEST_CONFIG_PATH="${{ secrets.AZURE_MS_TEST_CONFIG_PATH }}"
          export MS_CONFIG_PATH="${{ secrets.AZURE_MS_CONFIG_PATH }}"

          moonshot run my-run-1 qa-tests my-gpt-4o-mini
      
      - name: Upload Moonshot Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /app/data/results/*  
        
